# -*- coding: utf-8 -*-
"""Customer Churn Data Set [Kawu Musa "Mufasa", 15.08.2023].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iCrLLqRqoUvHuU-WVBc0I97ZPq6bX9Sw

# Machine Learning Project - Customer Churn Data Set [By Mufasa; (Currently Learning from Udemy)]

Link: https://www.kaggle.com/datasets/adammaus/predicting-churn-for-bank-customers?select=Churn_Modelling.csv

# Part 1 - Data Pre-processing

## Step 1 - Importing Libraries and Data set
"""

import numpy as np
import pandas as pd
import seaborn as sbn
import matplotlib.pyplot as plt

#reading csv file using pandas and saving into a variable called 'data'
data = pd.read_csv('/content/Churn_Modelling.csv')

#previewing the top 5 rows in the dataset
data.head()

"""## Step 2 - Data Exploration"""

#Finding out the number of rows and columns in the dataset
data.shape

#Obtaining basic information about the dataset
data.info()

#Finding the column that has categorical (Non-numerical) data.
data.select_dtypes(include='object').columns

#Finding the number of column(s) that have/has categorical (Non-numerical) data.
len(data.select_dtypes(include='object').columns)

#Finding the column(s) that have / has numerical data.
data.select_dtypes(include=['float64','int64']).columns

#Finding the number of column(s) that have / has numerical data.
len(data.select_dtypes(include=['float64','int64']).columns)

#Summarising statistical information about the columns in the dataset.
data.describe()

"""## Step 3 - Dealing with Missing values"""

#Are there null values in the dataset?
data.isnull().values.any()

#The number of null values in the dataset?
data.isnull().values.sum()

"""##Step 4 - Encoding Categorical Data"""

#Show the columns with non-numerical variables
data.select_dtypes(include='object').columns

#Remove columns that won't have any effect on prediction
data = data.drop(columns=['RowNumber','CustomerId','Surname'])

#Show unique categories in Geography column

data['Geography'].unique()

#Show unique categories in Gender column

data['Gender'].unique()

#Group dataset by Geography - Note the German-Balance

data.groupby('Geography').mean()

#Group dataset by Gender

data.groupby('Gender').mean()

#Apply one hot encoding to categorical variables

data = pd.get_dummies(data=data,drop_first=True)

data.head()

